Starting the refactoring of the sdk
swarmauri/swarmauri-sdk pull request #479
Opened 2024-09-20 09:22 UTC by 3rd-Son

Created new folders and their subfolders. Also created a `setup.py` for each
- swarmauri-community
- swarmauri-experimental

moved the necessary files and folders to the right folders.

I suggest you look into the `setup.py` files I created for `swarmauri-community` and `swarmauri-experimental` incase of corrections

2024-09-20 09:33 UTC, MichaelDecent commented
[](https://github.com/swarmauri/swarmauri-sdk/issues/476)

2024-09-20 09:37 UTC, RafaelJohn9 commented
solves #476

2024-09-20 21:20 UTC, cobycloud requested changes
remove all .DS_STORE and add .DS_STORE to the .gitnore

2024-09-21 09:50 UTC, cobycloud approved these changes

2024-09-21 09:50 UTC, merged