swarmauri - multimodal support
swarmauri/swarmauri-sdk pull request #599
Opened 2024-10-02 21:27 UTC by MichaelDecent

2024-10-03 07:44 UTC, MichaelDecent commented
Do you think i should add the image encoding logic to code, or the location of the function isn't right @RafaelJohn9

2024-10-03 07:54 UTC, RafaelJohn9 commented
> Do you think i should add the image encoding logic to code, or the location of the function isn't right @RafaelJohn9

hmmm

We might keep the function though I feel `validate model` function inside `HumanMessage` is too coupled with the file being an image

and about the `b64_encode_image` is also too focused on the file being an image what if we make it more generic  more like `b64_encoder`  function that accepts filepaths and retrieves the data whether being image, audio or video

2024-10-03 08:00 UTC, MichaelDecent commented
> > Do you think i should add the image encoding logic to code, or the location of the function isn't right @RafaelJohn9
> 
> hmmm
> 
> We might keep the function though I feel `validate model` function inside `HumanMessage` is too coupled with the file being an image
> 
> and about the `b64_encode_image` is also too focused on the file being an image what if we make it more generic more like `b64_encoder` function that accepts filepaths and retrieves the data whether being image, audio or video
> 
> @MichaelDecent

Yeah I get you. Agreed!
Will be making those changes as we progress in adding audio and video support.
Thanks man

Please keep dropping your reviews and feedback.

2024-10-03 10:59 UTC, cobycloud requested changes

2024-10-03 10:59 UTC, cobycloud commented on pkgs/swarmauri/tests/unit/llms/GroqModel_unit_test.py
let's bring back the use of the llama-guard-3b fixture, as we may develop multiple tests with it and want to ensure that all llama-guard specific-tests use the same fixture.

The model is very unique in its functionality and so we'll start researching for similar models, potentially they all get bundled into a class of their own for distinction.

2024-10-03 10:59 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/agents/concrete/SimpleConversationAgent.py
> +from pkgs.swarmauri.swarmauri.messages.concrete.HumanMessage import contentItem
never import from pkgs - it may work locally, but it simply won't work in this way when the packages are built

2024-10-03 10:59 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/messages/base/MessageBase.py
> +    content: Union[str, Dict, List[Dict]]
should we allow Dict here?

2024-10-03 10:59 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/messages/base/MessageBase.py
> +    content: Union[str, Dict, List[Dict]]
Have we found an example of Dict out in the wild? or only str and List[Dict]? please confirm

2024-10-03 10:59 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/messages/concrete/HumanMessage.py
> +    content: Optional[Union[str, List[contentItem]]]
the accepted typing between Human and Agent should probably be well aligned

2024-10-03 11:10 UTC, MichaelDecent commented on pkgs/swarmauri/swarmauri/messages/concrete/HumanMessage.py
> +    content: Optional[Union[str, List[contentItem]]]
Okay Noted.

2024-10-03 11:11 UTC, MichaelDecent commented on pkgs/swarmauri/swarmauri/messages/base/MessageBase.py
> +    content: Union[str, Dict, List[Dict]]
for now only `str` and `List[Dict]`

2024-10-03 11:11 UTC, MichaelDecent commented on pkgs/swarmauri/swarmauri/messages/base/MessageBase.py
> +    content: Union[str, Dict, List[Dict]]
i will make the neccessary update

2024-10-03 11:13 UTC, MichaelDecent commented on pkgs/swarmauri/tests/unit/llms/GroqModel_unit_test.py
I see. i miss interpreted. just wanted to keep thinks simple. making the requested changes ASAP

2024-10-03 11:18 UTC, MichaelDecent commented on pkgs/swarmauri/swarmauri/agents/concrete/SimpleConversationAgent.py
> +from pkgs.swarmauri.swarmauri.messages.concrete.HumanMessage import contentItem
Yeah i will correct that mistake. my IDE making imports without me confirming.

2024-10-03 16:37 UTC, RafaelJohn9 approved these changes
awesome work with the changes :+1:  on  `./swarmauri/base64_encoder.py`

2024-10-03 16:37 UTC, RafaelJohn9 commented on pkgs/swarmauri/swarmauri/utils/base64_image_encoder.py
@MichaelDecent  regarding this (*`/swarmauri/utils/base64_image_encoder.py`*)

do we really need it ?

2024-10-05 23:45 UTC, cobycloud approved these changes

2024-10-05 23:45 UTC, merged