Implement duckdb
swarmauri/swarmauri-sdk pull request #609
Opened 2024-10-06 06:41 UTC by RafaelJohn9

Fixed all DuckDB test cases

![image](https://github.com/user-attachments/assets/0b06b981-67c0-4809-85a0-e0b6bd209a42)

2024-10-08 01:24 UTC, cobycloud requested changes

2024-10-08 01:24 UTC, cobycloud commented on pkgs/community/setup.py
we only require duckdb

2024-10-08 03:32 UTC, RafaelJohn9 commented
done  :+1:

2024-10-09 10:22 UTC, cobycloud approved these changes

2024-10-09 10:24 UTC, merged