swarm - Add usage data tracking to MistralModel.py.
swarmauri/swarmauri-sdk pull request #706
Opened 2024-10-22 15:25 UTC by MichaelDecent

2024-10-23 10:37 UTC, cobycloud approved these changes

2024-10-23 12:04 UTC, cobycloud requested changes
minor changes

2024-10-23 12:04 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/llms/concrete/AI21StudioModel.py
> +            message_content = response.choices[0].message.content
this will only get the duration of the declaration, so we really only need prompt_timer

2024-10-23 12:07 UTC, MichaelDecent commented on pkgs/swarmauri/swarmauri/llms/concrete/AI21StudioModel.py
> +            message_content = response.choices[0].message.content
Noted

2024-10-24 04:10 UTC, cobycloud approved these changes

2024-10-24 04:10 UTC, merged