comm - fix errors related to community
swarmauri/swarmauri-sdk pull request #835
Opened 2024-11-21 15:39 UTC by MichaelDecent

2024-11-26 04:46 UTC, cobycloud approved these changes

2024-11-26 04:47 UTC, cobycloud requested changes
small fix to MlmEmbedding

2024-11-26 06:04 UTC, MichaelDecent commented
> small fix to MlmEmbedding

Yeah, i will add `sklearn` dependency package to pyproject file

2024-12-17 13:50 UTC, cobycloud approved these changes

2024-12-17 13:50 UTC, merged