Comm
swarmauri/swarmauri-sdk pull request #907
Opened 2024-12-11 14:28 UTC by 3rd-Son

@cobycloud 
I have implemented the `base class` and `core abstract` class for `transport`
Please give it a look and let me know if I should proceed with `concrete implementations` and `test cases`

2024-12-12 09:34 UTC, 3rd-Son commented on pkgs/core/swarmauri_core/transport/__init__.py
Thank you 
Didn't even know when I made this mistake

2024-12-12 14:58 UTC, 3rd-Son commented
@cobycloud please review my PR

2024-12-13 07:43 UTC, cobycloud requested changes
small changes requested. good work overall

2024-12-13 07:43 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/transport/base/TransportBase.py
> +    def subscribe(self, topic: str, subscriber: str) -> None:
what if we had an HTTPTransport base that has no inherent publish and subscribe methods?

2024-12-13 07:43 UTC, cobycloud commented on pkgs/core/swarmauri_core/transport/ITransport.py
> +class ITransportComm(ABC):
we'll drop the comm part and only refer to as Transport

2024-12-13 07:43 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/transport/base/TransportBase.py
> +class TransportationProtocol(Enum):
this might come in handy

2024-12-13 07:43 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/transport/base/TransportBase.py
> +    def subscribe(self, topic: str, subscriber: str) -> None:
If a transport is going to offer its own external methods for subscribe and publish, then it's likely doing so via a mixin.

As such, that would require a swarmauri_core/transport/IPubSub and a swarmauri/transport/base/PubSubMixin class. 

then at the concrete-level, if a transport is going to implement the IPubSub interface, it can do so via PubSubMixin,

2024-12-13 07:43 UTC, cobycloud commented on pkgs/swarmauri/tests/unit/transport/PubSubTransport_unit_test.py
include test methods to test:
- resource kind
- type
- serialization

2024-12-13 07:43 UTC, cobycloud commented on pkgs/swarmauri/swarmauri/transport/concrete/PubSubTransport.py
> +        subscriber_id = str(uuid4())
TransportBase inherits ComponentBase. All subclasses of ComponentBase automatically have an internal id accessible at

`self.id`

2024-12-13 08:15 UTC, 3rd-Son commented on pkgs/swarmauri/swarmauri/transport/base/TransportBase.py
> +    def subscribe(self, topic: str, subscriber: str) -> None:
ohh, now I see 
Great, I understand this

2024-12-13 12:26 UTC, 3rdsonx commented on pkgs/swarmauri/swarmauri/transport/concrete/PubSubTransport.py
Thank you @cobycloud

2024-12-17 13:51 UTC, cobycloud approved these changes

2024-12-17 13:51 UTC, merged